### ISSUE TITLE
Methods incorrectly configured

### ISSUE THREAD

**Issue by daniel-shuy** [xlsdg/vue-countup-v2#1]
I believe you've made a slight mistake in not putting the Vue methods in the `methods` block.

**Comment by xlsdg** [comment]
like this:

```js
import ICountUp from 'vue-countup-v2';
ICountUp.reset();
```

**Comment by daniel-shuy** [comment]
If a Vue Component instantiates multiple CountUp instances in its template, how would one reset only a specific CountUp?

**Comment by xlsdg** [comment]
Use `ready` event to get different instances.

**Comment by daniel-shuy** [comment]
I see... it still feels cumbersome to have to create a `data` field to store each instance.

May I suggest adding the methods to `methods` so that they can be called using `$refs` (similar to #2, but without removing the static methods)?
Eg.
`this.$refs.userCount.reset()`

**Comment by xlsdg** [comment]
You are right, I've already upgraded version to `v1.0.3`.
