### ISSUE TITLE
upgrade to countup.js@2

### ISSUE THREAD

**Issue by lianzhao** [xlsdg/vue-countup-v2#11]

**Comment by inorganik** [comment]
I second this! :)

New in 2.0:

- Rewritten in Typescript (distributed code is still javascript)
- New, cleaner method signature
- Jest tests
- Smart easing

Check it out! https://github.com/inorganik/countUp.js

**Comment by xlsdg** [comment]
Okay!

**Comment by xlsdg** [comment]
`v3.0.0` done.

**Comment by inorganik** [comment]
Nicely done!
