### ISSUE TITLE
"CountUp is not a constructor" error

### ISSUE THREAD

**Issue by NSpehler** [xlsdg/vue-countup-v2#12]
Hello there,

I'm getting the following error when using this package:

```
[Vue warn]: Error in mounted hook: "TypeError: CountUp is not a constructor"

found in

---> <ICountUp>
       <Home> at resources/js/views/Home.vue
         <App> at resources/js/views/App.vue
           <Root>
```

Any ideas what might cause this? I've copy-pasted the entire snippet from your exemple without luck.

Thanks,
Nicolas

**Comment by xlsdg** [comment]
`v3.0.1` fixed!
