### ISSUE TITLE
decimals属性无效？

### ISSUE THREAD

**Issue by DiamondsZz** [xlsdg/vue-countup-v2#25]
![image](https://user-images.githubusercontent.com/38370637/86898864-d04a8f80-c13b-11ea-8480-429b4e6775b9.png)

`<count-up :decimals="2" :endVal="88.888" />`
请问这个是什么原因？

**Comment by leozhang2018** [comment]
use decimalPlaces in option

**Comment by ZZHHzzhh** [comment]
> decimalPlaces

:options: {decimalPlaces: '2'}
