### ISSUE TITLE
decimalPlaces属性配置无效，不能保留二位小数

### ISSUE THREAD

**Issue by wenjunzhangp** [xlsdg/vue-countup-v2#26]
`countup.js` version `2.0.7`

`vue-countup-v2` version `4.0.0`

代码如下：
```
import ICountUp from 'vue-countup-v2';

components: {
    ICountUp
 },

<ICountUp :startVal="0"
    :endVal="88.25"
   :decimalPlaces="2"
   :duration="2"
  :options="options"
/>
```

效果图:

![image](https://user-images.githubusercontent.com/36065067/92483553-848b9380-f21b-11ea-9c4a-80cbc32f5f36.png)

**Comment by wenjunzhangp** [comment]
我好像知道原因了，`4.0.0`的版本中跟本没有 `decimalPlaces` 这个属性

**Comment by wenjunzhangp** [comment]
解决办法是在 `options` 中定义 `decimalPlaces` 字段。

**Comment by cdecinkoKnight** [comment]
Why was this not documented?  How do I pass a dynamic value when that is the only option I need to change on the fly?
