### ISSUE TITLE
How to access methods from outside the component?

### ISSUE THREAD

**Issue by devanflaherty** [xlsdg/vue-countup-v2#5]
Hey there,
I'm wanting to initially my countUp pause until triggered by a scroll event.

Not sure how to get access to the instance outside the component, any advice?

**Comment by xlsdg** [comment]
`@ready` can get instance, see https://github.com/xlsdg/vue-countup-v2-demo.

**Comment by xlsdg** [comment]
Or `this.$refs.xxxxxxx.reset()` .

**Comment by devanflaherty** [comment]
Thanks!
