### ISSUE TITLE
multiple CountUp

### ISSUE THREAD

**Issue by robertnicjoo** [xlsdg/vue-countup-v2#8]
Hi,

Is more like question than issue,

How can I have multiple CountUp in my component? let say:

```html

Posts               users             comments
5000                1680              13678
```

How can I define differences?

**Comment by paulbremer** [comment]
Make sure you bind the values of the different numbers to the end value, for example; 
`<ICountUp
    :endVal="posts"
  />`
`<ICountUp
    :endVal="users"
  />`
`<ICountUp
    :endVal="comments"
  />`
